remove openssh update from dropbear hack
commit d35a2f5aa6e47c9565f1669eec3184d032e3a653
Author: Tobias Hintze <thintze+git@tpip.net>
Date:   Tue Jun 2 23:49:27 2015 +0200

    make openssh an upgrade of dropbear

causes the build to fail on fido
ERROR: Unable to install packages. Command '/usr/src/poky/build/tmp/sysroots/x86_64-linux/usr/bin/smart --quiet --data-dir=/usr/src/poky/build/tmp/work/sun7i_a20_lamobo_r1-caros-linux-gnueabi/core-image-caros/1.0-r0/rootfs/var/lib/smart install -y psplash@armv7a_vfp_neon swconfig@armv7a_vfp_neon smartpm@armv7a_vfp_neon packagegroup-core-ssh-openssh@all vlan@armv7a_vfp_neon iw@armv7a_vfp_neon linux-firmware-rtl8192cu@all shadow@armv7a_vfp_neon packagegroup-base-extended@sun7i_a20_lamobo_r1 rpm@armv7a_vfp_neon base-passwd@armv7a_vfp_neon packagegroup-core-boot@sun7i_a20_lamobo_r1 locale-base-en-us@armv7a_vfp_neon locale-base-en-gb@armv7a_vfp_neon' returned 1:
error: Can't install openssh-6.7p1-r0.1@armv7a_vfp_neon: unable to install provider for openssh-sshd:
error:     openssh-sshd-6.7p1-r0.1@armv7a_vfp_neon is conflicted by openssh-6.7p1-r0.1@armv7a_vfp_neon

Thus revert it for now until it's necessity is assured and
a better fix is found.